// <auto-generated />
using System;
using Fuel_Tracking_application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelTrackingapplication.Migrations
{
    [DbContext(typeof(FuelDbContext))]
    [Migration("20230201182832_Update5")]
    partial class Update5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fuel_Tracking_application.Models.Domain.Fuel", b =>
                {
                    b.Property<Guid>("dataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("fillStationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("filled")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<double>("filledVolume")
                        .HasColumnType("float");

                    b.Property<double>("fuelPrice")
                        .HasColumnType("float");

                    b.Property<string>("fuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("reportingEmployee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siteLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleregistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dataId");

                    b.ToTable("FuelData");
                });
#pragma warning restore 612, 618
        }
    }
}
